version: "2"

services:
  green-living:
    container_name: green-living
    build:
      context: .
    ports:
      - "8000:80"
    environment:
      ENV: dev
    volumes:
      - ./project:/srv/project
    #   - ./tests:/srv/tests
    #   - ./test.py:/srv/test.py
    #   - ./ui/public:/srv/ui/public
    #   - ./ui/src:/srv/ui/src
    #   - ./ui/static:/srv/ui/static
    #   - ./data/photos:/data/photos
    #   - ./data/raw-photos-processed:/data/raw-photos-processed
    #   - ./data/cache:/data/cache
    #   - ./data/models:/data/models
    #   - ./system/supervisord.conf:/etc/supervisord.conf
