# Generated by Django 2.2.7 on 2020-01-25 15:47

from django.conf import settings
from django.db import migrations
import django.db.models.deletion
import filer.fields.image


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='business_logo',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place_business_logo', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='place',
            name='photo1',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place_photo1', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='place',
            name='photo2',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place_photo2', to=settings.FILER_IMAGE_MODEL),
        ),
        migrations.AlterField(
            model_name='place',
            name='thumbnail',
            field=filer.fields.image.FilerImageField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='place_thumbnail', to=settings.FILER_IMAGE_MODEL),
        ),
    ]
