# Generated by Django 2.2.13 on 2023-01-06 14:42

from django.db import migrations


def populate_updated_at(apps, schema_editor):
    Place = apps.get_model('places', 'Place')
    for place in Place.objects.all():
        if not place.updated_at:
            place.updated_at = place.created_at
            place.save()


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0003_place_updated_at'),
    ]

    operations = [
        migrations.RunPython(populate_updated_at),
    ]
